### ISSUE TITLE
Failure after updating JavaSMT

### ISSUE THREAD

**Issue by PavelAndrianov** [sosy-lab/java-smt#146]
After updating JavaSMT in CPAchecker (r29458), SMTInterpol fails with assertion: 
`Exception in thread "main" java.lang.AssertionError
	at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.linar.LinArSolve.mbtc(LinArSolve.java:2061)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.linar.LinArSolve.computeConflictClause(LinArSolve.java:618)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.checkConsistency(DPLLEngine.java:1027)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.solve(DPLLEngine.java:1171)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol$CheckType$1.check(SMTInterpol.java:114)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.checkSatAssuming(SMTInterpol.java:502)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.checkSat(SMTInterpol.java:455)
	at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolEnvironment.checkSat(SmtInterpolEnvironment.java:310)
	at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolAbstractProver.isUnsat(SmtInterpolAbstractProver.java:94)
	at org.sosy_lab.java_smt.basicimpl.reusableStack.ReusableStackAbstractProver.isUnsat(ReusableStackAbstractProver.java:56)
	at org.sosy_lab.java_smt.basicimpl.reusableStack.ReusableStackTheoremProver.isUnsat(ReusableStackTheoremProver.java:25)
	at org.sosy_lab.java_smt.basicimpl.withAssumptionsWrapper.BasicProverWithAssumptionsWrapper.isUnsat(BasicProverWithAssumptionsWrapper.java:70)
	at org.sosy_lab.cpachecker.util.predicates.smt.BasicProverEnvironmentView.isUnsat(BasicProverEnvironmentView.java:71)
	at org.sosy_lab.cpachecker.cpa.predicate.PredicateAbstractionManager.computeAbstraction(PredicateAbstractionManager.java:772)
	at org.sosy_lab.cpachecker.cpa.predicate.PredicateAbstractionManager.buildAbstraction(PredicateAbstractionManager.java:436)
	at org.sosy_lab.cpachecker.cpa.predicate.PredicatePrecisionAdjustment.computeAbstraction(PredicatePrecisionAdjustment.java:186)
	at org.sosy_lab.cpachecker.cpa.predicate.PredicatePrecisionAdjustment.prec(PredicatePrecisionAdjustment.java:105)
	at org.sosy_lab.cpachecker.cpa.composite.CompositePrecisionAdjustment.prec(CompositePrecisionAdjustment.java:86)
	at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:96)
	at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:70)
	at org.sosy_lab.cpachecker.cpa.bam.BAMPrecisionAdjustment.prec(BAMPrecisionAdjustment.java:81)
	at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.handleState(CPAAlgorithm.java:358)
	at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run0(CPAAlgorithm.java:291)
	at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run(CPAAlgorithm.java:223)
	at org.sosy_lab.cpachecker.core.algorithm.CEGARAlgorithm.run(CEGARAlgorithm.java:241)
	at org.sosy_lab.cpachecker.core.CPAchecker.runAlgorithm(CPAchecker.java:542)
	at org.sosy_lab.cpachecker.core.CPAchecker.run(CPAchecker.java:412)
	at org.sosy_lab.cpachecker.cmdline.CPAMain.main(CPAMain.java:168)`

The command line is the following `scripts/cpa.sh -predicateAnalysis-bam -setprop "solver.solver=SMTInterpol" -setprop "cpa.predicate.encodeBitvectorAs=INTEGER" -setprop "cpa.predicate.encodeFloatAs=RATIONAL" -setprop "cpa.predicate.checkBlockFeasibility=true" solver-exception.c`

The assertion occurs even without `cpa.predicate.checkBlockFeasibility=true`, but this requires much more complicated task. 
An interesting moment is that the problem does not occur without BAM. 

BTW, I did not understand, how it is possible to attach `.c` files, so, I just renamed it. 
[solver-exception.txt](https://github.com/sosy-lab/java-smt/files/2796281/solver-exception.txt)

**Comment by kfriedberger** [comment]
Thanks for @jhoenicke for updating the Maven release.
CPAchecker ([trunk@r30539](https://gitlab.com/sosy-lab/software/cpachecker/commit/aedd156ba82f113a0071d14595ae6c06a736b5bd)) got updated. Closing.
