### ISSUE TITLE
Classloader does not find Java classes for Z3 on Java 10 or newer 

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#155]
The following cmdline works well on Java8, but not on Java10 and Java11. Java9 was not tested.
Other solvers (like MathSAT5) or other usages (like Z3 within CPAchecker on Java10 or JUnit tests on Java10) are not affected and work as expected.

**Cmdline**:
<pre>
export CLASSPATH=:bin:JAVASMT.jar:lib/*:lib/java/runtime/*
java org.sosy_lab.java_smt.example.HoudiniApp
</pre>

**The following exception appears**:
<pre>
Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/z3/Native
        at org.sosy_lab.java_smt.solvers.z3.Z3SolverContext.create(Z3SolverContext.java:165)
        at org.sosy_lab.java_smt.solvers.z3.Z3LoadingFactory.generateSolverContext(Z3LoadingFactory.java:53)
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext0(SolverContextFactory.java:197)
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:158)
        at org.sosy_lab.java_smt.SolverContextFactory.createSolverContext(SolverContextFactory.java:237)
        at org.sosy_lab.java_smt.example.HoudiniApp.main(HoudiniApp.java:64)
Caused by: java.lang.ClassNotFoundException: com.microsoft.z3.Native
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at org.sosy_lab.common.ExtendedURLClassLoader.loadClass(ExtendedURLClassLoader.java:85)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 6 more
</pre>

**Wanted Solution**:
The script `runExamples.sh` uses such a cmdline to execute examples.
Either that script or the Java code for loading a library should be fixed.

**Comment by PhilippWendler** [comment]
This is because on Java 9, [the regular class loader is no longer a `URLClassLoader`](https://blog.codefx.org/java/java-9-migration-guide/#Casting-To-URL-Class-Loader). We relied on this for setting the class path of our own class loader that loads Z3:
https://github.com/sosy-lab/java-smt/blob/4095798f0ae7c9b4b41cff58b472216d134860ce/src/org/sosy_lab/java_smt/SolverContextFactory.java#L312-L318
Without a `URLClassLoader`, we get only the URL for the JavaSMT classes, but not for the Z3 classes.

We need a new way to get the URL for the `com.microsoft.z3.jar` out of the current class loader on Java 9+.

**Comment by kfriedberger** [comment]
@PhilippWendler 
Thanks for the fix. Just a remaining question:
Why did Z3 work as part of CPAchecker on Java9?

**Comment by PhilippWendler** [comment]
Not fully sure, my guess would be that it is because `javasmt.jar` declares `com.microsoft.z3.jar` as dependency in its manifest file. So maybe the class loader automatically follows this dependency, but of course this works only if both JARs are in the same directory (because the dependency is treated as a file name relative to the declaring JAR file).
