### ISSUE TITLE
Compilation Problem after Build with Eclipse Compiler

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#193]
Building JavaSMT with the Eclipse compiler works.
However executing the steps `ant clean; ant build-project-ecj; ./runExamples.sh` reports an error:
<pre>
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
Type safety: Unchecked cast from Class<capture#1-of ?> to Class<? extends SolverContextFactory.InnerUtilFactory>
at org.sosy_lab.java_smt.SolverContextFactory.getFactoryForSolver(SolverContextFactory.java:334)
at org.sosy_lab.java_smt.SolverContextFactory.generateContext0(SolverContextFactory.java:232)
at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:179)
at org.sosy_lab.java_smt.SolverContextFactory.createSolverContext(SolverContextFactory.java:276)
at org.sosy_lab.java_smt.example.OptimizationFormulaWeights.main(OptimizationFormulaWeights.java:43)
</pre>

@PhilippWendler Is this a bug in the Eclipse compiler?

**Comment by PhilippWendler** [comment]
I can reproduce this. It occurs at least with ECJ 4.16, 4.14, and 4.11. So it is not a recent regression.

In contrast to javac, ECJ can continue compilation even if compile errors occur (for certain kinds of errors). In such a case, it inserts code that throws an exception if the problematic code is reached at runtime. This is obviously what happens here, it is just the question why this error ends up in the compiled code but is not reported during compilation.

The code in question here is an unchecked cast that has a `@SuppressWarnings`.

There are two configuration options of Eclipse that affect this. One is to treat all optional configured errors as fatal errors (i.e., inserting code that throws this exception) and one is to allow the use of `@SuppressWarnings` for optional configured errors. Both are enabled in our case. Unchecked casts are configured as warnings.

We use almost the same configuration for our in-Eclipse builds and `build-project-ecj`. The latter copies `.settings/org.eclipse.jdt.core.prefs` and raises the severity of all warnings to errors. This is done to let the build fail in case a warning exists.

So I now have a hypothesis:
- In Eclipse, the unchecked cast is a warning. `@SuppressWarnings` is allowed and suppresses it, and it is not turned into a fatal error (exception) because it is just a warning, not an error.
- When building with `build-project-ecj`, the unchecked cast is an error. `@SuppressWarnings` is allowed and suppresses it, but it it still turned into a fatal error because it is an error.

This seems to be confirmed by the following experiment:
If I run `sed -e 's/=warning$/=error/' .settings/org.eclipse.jdt.core.prefs -i` to raise all Eclipse warnings to errors, rebuild, and execute `AllSatExample` from within Eclipse, it fails with the same exception (although Eclipse does not show any error in the Problem view). (For doing this a few more modules are necessary to be added to `.classpath`).

This would also explain why it has not been noticed before: All executed code was either compiled from within Eclipse (e.g., when running unit tests interactively) or with standard `ant build`. Compilation with `ant build-project-ecj` was only used for checking and the result discarded.

I would still say that this is a bug or an unfortunate design decision of the Eclipse compiler that `@SuppressWarnings` suppresses the compiler output but has no effect on errors that are turned into fatal errors.

My suggestion would be to search on the net if there is a solution. Otherwise, we could investigate the following workarounds:
- Find a solution that fails the build if any warning exists without needing to configure each warning as an error. Maybe ECJ supports `-Werror` or something like this?
- Disable the option for making all optional errors fatal errors. Not sure whether this would have any disadvantages?
- Declare `build-project-ecj` as being there only for checking, not for producing binaries. We can even create a temp directory as compiler target such that it does not overwrite the existing class files and always compiles every class instead of doing an incremental build. This trick is used for Refaster as well, btw.

**Comment by PhilippWendler** [comment]
No longer occurs.
