### ISSUE TITLE
MathSAT 5.6.4 can not build a model for LIA+Array

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#209]
CPAchecker fails with exceptions for several tasks.
More details: https://gitlab.com/sosy-lab/software/cpachecker/-/issues/795

We need to look at MathSAT5 again.
Do we need to adjust our JNI wrapper or is there a bug in MathSAT5 itself?

The stacktrace is:
<pre>
Exception in thread "main" java.lang.IllegalArgumentException: MathSAT returned null
at org.sosy_lab.java_smt.solvers.mathsat5.Mathsat5NativeApi.msat_model_create_iterator(Native Method)
at org.sosy_lab.java_smt.solvers.mathsat5.Mathsat5Model.toList(Mathsat5Model.java:57)
at org.sosy_lab.java_smt.basicimpl.AbstractModel$CachingAbstractModel.asList(AbstractModel.java:109)
at org.sosy_lab.java_smt.api.BasicProverEnvironment.getModelAssignments(BasicProverEnvironment.java:80)
...
</pre>

**Comment by kfriedberger** [comment]
The following SMT query returns `invalid model` directly from MathSAT 5.6.4.

<pre>
(set-option :global-declarations true)
(set-option :config "model_generation=true")
(set-option :config "bool_model_generation=false")  // <--- changing this value helps
(set-option :config "random_seed=42")
(set-option :config "printer.model_as_formula=false")

(push 1)
(declare-fun |__ADDRESS_OF_main::a@| () Int)
(declare-fun |main::a@2| () Int)
(declare-fun *int@1 () (Array Int Int))
(declare-fun |main::p@2| () Int)
(declare-fun *int@2 () (Array Int Int))
(define-fun .8 () Int 0)
(define-fun .13 () Int |__ADDRESS_OF_main::a@|)
(define-fun .14 () Bool (<= .13 .8))
(define-fun .15 () Bool (not .14))
(define-fun .16 () Bool ((_ divisible 4) (- .13 .8)))
(define-fun .18 () Int (- 4))
(define-fun .19 () Bool (<= .13 .18))
(define-fun .20 () Bool (not .19))
(define-fun .21 () Int |main::a@2|)
(define-fun .22 () Bool (= .21 .8))
(define-fun .23 () Bool (and .15 .16))
(define-fun .24 () Bool (and .20 .23))
(define-fun .25 () Bool (and .22 .24))
(assert .25)
(check-sat)
(get-model)
</pre>

It was dumped from CPAchecker r35563 with the following command line:  
`scripts/cpa.sh -predicateAnalysis-linear -spec test/config/properties/unreach-label.prp test/programs/simple/pointerDereferenceWithDirectVarAssignment.c -setprop solver.logAllQueries=true`  
and the minified

**Comment by kfriedberger** [comment]
Status: Bug has been reported to Alberto.

**Comment by kfriedberger** [comment]
Problem disappeared after last MathSAT update.
