### ISSUE TITLE
Maven configuration for bitwuzla

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#386]
I am trying to update the used version of javasmt in our project and wanted to test how the new smt solver bitwuzla performs.

Unfortunately, the documentation with maven configuration examples was not updated I am not 100% sure which dependencies need to be added.

So far, I changed our `pom.xml` file as follows
```
    <profiles>
        <profile>
            <id>linux</id>
            <dependencies>
...
                <!-- Bitwuzla dependencies -->
                <dependency>
                    <groupId>org.sosy-lab</groupId>
                    <artifactId>javasmt-solver-bitwuzla</artifactId>
                    <version>${bitwuzla.version}</version>
                    <classifier>libbitwuzlaj</classifier>
                    <type>so</type>
                </dependency>
```
and
```
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <artifactId>maven-dependency-plugin</artifactId>
                            <configuration>

...
                                    <!-- Bitwuzla dependencies -->
                                    <artifactItem>
                                        <groupId>org.sosy-lab</groupId>
                                        <artifactId>javasmt-solver-bitwuzla</artifactId>
                                        <type>so</type>
                                        <classifier>libbitwuzlaj</classifier>
                                        <destFileName>libbitwuzlaj.so</destFileName>
                                    </artifactItem>
```
However, I get the following error
```
org.sosy_lab.common.configuration.InvalidConfigurationException: The SMT solver BITWUZLA is not available on this machine because of missing libraries (org/sosy_lab/java_smt/solvers/bitwuzla/api/TermManager).
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:217) ~[java-smt-5.0.0.jar:5.0.0]
        at org.sosy_lab.java_smt.SolverContextFactory.createSolverContext(SolverContextFactory.java:333) ~[java-smt-5.0.0.jar:5.0.0]
        at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:161) [dartagnan.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/sosy_lab/java_smt/solvers/bitwuzla/api/TermManager
        at org.sosy_lab.java_smt.solvers.bitwuzla.BitwuzlaSolverContext.create(BitwuzlaSolverContext.java:148) ~[java-smt-5.0.0.jar:5.0.0]
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext0(SolverContextFactory.java:304) ~[java-smt-5.0.0.jar:5.0.0]
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:214) ~[java-smt-5.0.0.jar:5.0.0]
        ... 2 more
Caused by: java.lang.ClassNotFoundException: org.sosy_lab.java_smt.solvers.bitwuzla.api.TermManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at org.sosy_lab.java_smt.solvers.bitwuzla.BitwuzlaSolverContext.create(BitwuzlaSolverContext.java:148) ~[java-smt-5.0.0.jar:5.0.0]
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext0(SolverContextFactory.java:304) ~[java-smt-5.0.0.jar:5.0.0]
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:214) ~[java-smt-5.0.0.jar:5.0.0]
```
Am I missing anything in the maven configuration?

**Comment by kfriedberger** [comment]
Could you take a look at the changes that i made yesterday: 1d4cc82cc6b10ce7897b277d69f8eda7a8f3b275
I tried the example project and it worked.

**Comment by hernanponcedeleon** [comment]
> Could you take a look at the changes from yesterday: [1d4cc82](https://github.com/sosy-lab/java-smt/commit/1d4cc82cc6b10ce7897b277d69f8eda7a8f3b275) I tried the example project and it worked.

Sorry, I missed this commit.

> 
> Maybe a dependency is missing:
> 
> ```
>     <dependency>
>       <groupId>org.sosy-lab</groupId>
>       <artifactId>javasmt-solver-bitwuzla</artifactId>
>       <version>${bitwuzla.version}</version>
>       <type>jar</type>
>       <classifier>bitwuzla</classifier>
>     </dependency>
> ```

Yes, all works now that I added this dependency.

Thanks @kfriedberger
