### ISSUE TITLE
Exception when Z3 is interrupted during Model.evaluate()

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#406]
Same as #291, just for a different entry point:
```
Exception in thread "main" com.microsoft.z3.Z3Exception: canceled
	at com.microsoft.z3.Native.modelEval(Native.java:3948)
	at org.sosy_lab.java_smt.solvers.z3.Z3Model.evalImpl(Z3Model.java:380)
	at org.sosy_lab.java_smt.solvers.z3.Z3Model.evalImpl(Z3Model.java:27)
	at org.sosy_lab.java_smt.basicimpl.AbstractEvaluator.evaluateImpl(AbstractEvaluator.java:127)
	at org.sosy_lab.java_smt.basicimpl.AbstractEvaluator.evaluate(AbstractEvaluator.java:109)
	at org.sosy_lab.java_smt.basicimpl.CachingModel.evaluate(CachingModel.java:57)
	at org.sosy_lab.cpachecker.util.predicates.smt.ModelView.evaluateImpl(ModelView.java:50)
	at org.sosy_lab.cpachecker.util.predicates.smt.ModelView.evaluate(ModelView.java:56)
[...]
```
Occurs with JavaSMT 5.0 and Z3 4.12.5.0. Full stack trace available [here](https://buildbot.sosy-lab.org/cpachecker/results/policyIteration/01513.-r_integration-policyIteration.2024-10-28_16-38-17.results.html#/table?filter=0(0*status*(status(in(TIMEOUT%20%28EXCEPTION%29)),category(notIn())))).

JavaSMT should ensure that all calls into Z3 handle interruptions appropriately and translate them into `InterruptedException`s.

**Comment by baierd** [comment]
I added the correct Exception in a new [branch](https://github.com/sosy-lab/java-smt/tree/406-exception-when-z3-is-interrupted-during-modelevaluate) . I guess we should discuss this in PR #407.
