### ISSUE TITLE
Missing array handling in Z3Model

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#95]
In some cases, I get the error `IllegalArgumentException: Unexpected type encountered: Array` when retrieving a model from Z3.

Example for reproduction with CPAchecker:
```
scripts/cpa.sh -setprop cpa.predicate.memoryAllocationsAlwaysSucceed=true -predicateAnalysis-heaparray -setprop cpa.predicate.encodeBitvectorAs=BITVECTOR -setprop cpa.predicate.encodeFloatAs=FLOAT -setprop cpa.predicate.handleFieldAccess=true -setprop solver.solver=z3 -setprop cpa.predicate.useQuantifiersOnArrays=true -spec sv-comp-reachability test/programs/benchmarks/floats-cbmc-regression/float7_true-unreach-call.i -disable-java-assertions
```
Stacktrace:
```
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected type encountered: Array
	at org.sosy_lab.java_smt.solvers.z3.Z3FormulaCreator.convertValue(Z3FormulaCreator.java:550)
	at org.sosy_lab.java_smt.solvers.z3.Z3Model.getFunctionAssignment(Z3Model.java:278)
	at org.sosy_lab.java_smt.solvers.z3.Z3Model.getFunctionAssignments(Z3Model.java:252)
	at org.sosy_lab.java_smt.solvers.z3.Z3Model.modelToList(Z3Model.java:95)
	at org.sosy_lab.java_smt.solvers.z3.Z3AbstractProver.getModelAssignments(Z3AbstractProver.java:51)
	at org.sosy_lab.cpachecker.util.predicates.smt.InterpolatingProverEnvironmentView.getModelAssignments(InterpolatingProverEnvironmentView.java:84)
	at org.sosy_lab.cpachecker.util.predicates.interpolation.InterpolationManager.getErrorPath(InterpolationManager.java:615)
	at org.sosy_lab.cpachecker.util.predicates.interpolation.InterpolationManager.access$1300(InterpolationManager.java:95)
	at org.sosy_lab.cpachecker.util.predicates.interpolation.InterpolationManager$Interpolator.buildCounterexampleTrace(InterpolationManager.java:779)
	at org.sosy_lab.cpachecker.util.predicates.interpolation.InterpolationManager$Interpolator.access$100(InterpolationManager.java:674)
	at org.sosy_lab.cpachecker.util.predicates.interpolation.InterpolationManager.buildCounterexampleTrace0(InterpolationManager.java:324)
	at org.sosy_lab.cpachecker.util.predicates.interpolation.InterpolationManager.buildCounterexampleTrace(InterpolationManager.java:238)
	at org.sosy_lab.cpachecker.cpa.predicate.PredicateStaticRefiner.performStaticRefinementForPath(PredicateStaticRefiner.java:220)
	at org.sosy_lab.cpachecker.cpa.predicate.PredicateStaticRefiner.performRefinementForPath(PredicateStaticRefiner.java:189)
	at org.sosy_lab.cpachecker.cpa.arg.AbstractARGBasedRefiner.performRefinementForPath(AbstractARGBasedRefiner.java:166)
	at org.sosy_lab.cpachecker.cpa.arg.AbstractARGBasedRefiner.performRefinement(AbstractARGBasedRefiner.java:120)
	at org.sosy_lab.cpachecker.core.algorithm.CEGARAlgorithm.refine(CEGARAlgorithm.java:257)
	at org.sosy_lab.cpachecker.core.algorithm.CEGARAlgorithm.run(CEGARAlgorithm.java:202)
	at org.sosy_lab.cpachecker.core.CPAchecker.runAlgorithm(CPAchecker.java:478)
	at org.sosy_lab.cpachecker.core.CPAchecker.run(CPAchecker.java:355)
	at org.sosy_lab.cpachecker.cmdline.CPAMain.main(CPAMain.java:159)
```
If I enable assertions, the error changes to `AssertionError: value is not constant`.

**Comment by cheshire** [comment]
Yup, we were silently converting all such values to strings before, but then that was changed to crash on unexpected values.
What should be the expected behavior? Returning `Object[]`? Or `List<Object>`?

**Comment by PhilippWendler** [comment]
Why does it seem to work for unit tests like `ModelTest.testGetArrays()` though?

The expected behavior would be the same as for the other solvers, which is expansion of the array and returning a `ValueAssignment` for each cell where the SMT solver assigns a value.

**Comment by kfriedberger** [comment]
The current implementation aims to split up arrays into their assignments, such that the RHS of the assignment is always a value of simple type (boolean, numeral, or bitvector). From one array-assignment in Z3Model we get (at least) N assignments in the returned assignment-list of the model. 
I currently do not know what goes wrong here.

**Comment by cheshire** [comment]
@PhilippWendler from what I understand the test tests calling `evaluate`, which does not require serializing, and iteration.
In any case, "proper" conversion to Java datastructures is missing.
@kfriedberger What about arrays where we don't know the length? It doesn't seem like a good way to go.

**Comment by kfriedberger** [comment]
We never know an array's length here. But the Z3Model assigns a value to each array cell by defining an ITE structure (`if ... else if ... else if ... else if ... else`) switching over the index of the cell. We split up the ITE structure.

**Comment by PhilippWendler** [comment]
Any chance to get this fixed? Interestingly, it does not occur with linear arithmetic (omitting the `-setprop cpa.predicate.encodeBitvectorAs=BITVECTOR -setprop cpa.predicate.encodeFloatAs=FLOAT`).

Furthermore, there is also another problem related to array models of Z3, as can again be seen in CPAchecker:
```
scripts/cpa.sh -policy-refinement -setprop cpa.predicate.useArraysForHeap=true -spec sv-comp-reachability test/programs/benchmarks/loops/bubble_sort_false-unreach-call.i
```
gives
```
Exception in thread "main" java.lang.UnsupportedOperationException: unknown model evaluation: ((as const (Array Int Int)) 0)
        at org.sosy_lab.java_smt.solvers.z3.Z3Model.getConstAssignments(Z3Model.java:141)
        at org.sosy_lab.java_smt.solvers.z3.Z3Model.modelToList(Z3Model.java:84)
        at org.sosy_lab.java_smt.basicimpl.AbstractModel$CachingAbstractModel.iterator(AbstractModel.java:97)
        at org.sosy_lab.cpachecker.util.predicates.smt.ModelView.iterator(ModelView.java:100)
        at org.sosy_lab.cpachecker.cpa.policyiteration.FormulaLinearizationManager.enforceChoice(FormulaLinearizationManager.java:120)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.modelToPolicyBound(PolicyIterationManager.java:1144)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.getPolicyBound(PolicyIterationManager.java:768)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.performAbstraction(PolicyIterationManager.java:915)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.strengthen(PolicyIterationManager.java:410)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyCPA.strengthen(PolicyCPA.java:249)
        at org.sosy_lab.cpachecker.cpa.composite.CompositePrecisionAdjustment.callStrengthen(CompositePrecisionAdjustment.java:146)
        at org.sosy_lab.cpachecker.cpa.composite.CompositePrecisionAdjustment.prec(CompositePrecisionAdjustment.java:116)
        at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:96)
        at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:70)
        at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.handleState(CPAAlgorithm.java:308)
        at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run0(CPAAlgorithm.java:241)
        at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run(CPAAlgorithm.java:207)
        at org.sosy_lab.cpachecker.core.algorithm.CEGARAlgorithm.run(CEGARAlgorithm.java:204)
        at org.sosy_lab.cpachecker.core.CPAchecker.runAlgorithm(CPAchecker.java:481)
        at org.sosy_lab.cpachecker.core.CPAchecker.run(CPAchecker.java:360)
        at org.sosy_lab.cpachecker.cmdline.CPAMain.main(CPAMain.java:171)
```

**Comment by PhilippWendler** [comment]
This is not fixed. For the [original problem](https://github.com/sosy-lab/java-smt/issues/95#issue-199485015), the command line with a current CPAchecker is now
```
scripts/cpa.sh -setprop cpa.predicate.memoryAllocationsAlwaysSucceed=true -predicateAnalysis-linear -setprop cpa.predicate.encodeBitvectorAs=BITVECTOR -setprop cpa.predicate.encodeFloatAs=FLOAT -setprop cpa.predicate.handleFieldAccess=true -setprop solver.solver=z3 -setprop cpa.predicate.useQuantifiersOnArrays=true -spec sv-comp-reachability test/programs/benchmarks/floats-cbmc-regression/float7_true-unreach-call.i -disable-java-assertions
```
and the exception remains the same (`Unexpected type encountered: Array`).

For the [other problem](https://github.com/sosy-lab/java-smt/issues/95#issuecomment-330152894), updating to JavaSMT 05d8a24 now produces the following exception:
```
Exception in thread "main" java.lang.UnsupportedOperationException: unknown model evaluation: (let ((a!1 (store (store (store ((as const (Array Int Int)) 0) 4 70) 70 0) 74 1)))
(let ((a!2 (store (store (store (store a!1 1 70) 78 78) 74 231) 231 70)))
  (store (store (store a!2 235 1) 1 231) 239 239)))
        at org.sosy_lab.java_smt.solvers.z3.Z3Model.getConstAssignments(Z3Model.java:155)
        at org.sosy_lab.java_smt.solvers.z3.Z3Model.modelToList(Z3Model.java:84)
        at org.sosy_lab.java_smt.basicimpl.AbstractModel$CachingAbstractModel.iterator(AbstractModel.java:97)
        at org.sosy_lab.cpachecker.util.predicates.smt.ModelView.iterator(ModelView.java:100)
        at org.sosy_lab.cpachecker.cpa.policyiteration.FormulaLinearizationManager.enforceChoice(FormulaLinearizationManager.java:120)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.modelToPolicyBound(PolicyIterationManager.java:1144)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.getPolicyBound(PolicyIterationManager.java:768)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.performAbstraction(PolicyIterationManager.java:915)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.strengthen(PolicyIterationManager.java:410)
        at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyCPA.strengthen(PolicyCPA.java:249)
        at org.sosy_lab.cpachecker.cpa.composite.CompositePrecisionAdjustment.callStrengthen(CompositePrecisionAdjustment.java:146)
        at org.sosy_lab.cpachecker.cpa.composite.CompositePrecisionAdjustment.prec(CompositePrecisionAdjustment.java:116)
        at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:96)
        at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:70)
        at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.handleState(CPAAlgorithm.java:308)
        at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run0(CPAAlgorithm.java:241)
        at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run(CPAAlgorithm.java:207)
        at org.sosy_lab.cpachecker.core.algorithm.CEGARAlgorithm.run(CEGARAlgorithm.java:204)
        at org.sosy_lab.cpachecker.core.CPAchecker.runAlgorithm(CPAchecker.java:481)
        at org.sosy_lab.cpachecker.core.CPAchecker.run(CPAchecker.java:360)
        at org.sosy_lab.cpachecker.cmdline.CPAMain.main(CPAMain.java:171)
```

**Comment by kfriedberger** [comment]
maybe we have all cases now:
0b892520bb82345e174251f43fa71f5c25364e70 , 4062d3eda733023db0cb9a538d51613bcc268389
